// subrange.cpp: implementation of the CSubRange class.
//
//////////////////////////////////////////////////////////////////////

#include "StdAfx.h"
#include "subrange.h"


#ifdef _DEBUG
#undef THIS_FILE
static char THIS_FILE[]= __FILE__;
#define new DEBUG_NEW
#endif


CSubRange::CSubRange() {
    Init( -MAXLONG, -MAXLONG, false, 0 );
}

CSubRange::CSubRange( double iLow, double iHigh, bool bHighImplicit, int iCollapsed ) {
    Init( iLow, iHigh, bHighImplicit, iCollapsed );
}

void CSubRange::Init( double iLow, double iHigh, bool bHighImplicit, int iCollapsed ) {
    m_iLow = iLow;
    m_iHigh = iHigh;
    m_iCollapsed  = iCollapsed;
    m_bHighImplicit = bHighImplicit;
}

// Access methods
// Number of cells generated by this range. If the range is collapsed then only the first range generate 1 cell
int CSubRange::GetNumCells() {
    int     iNumCells;

    if( m_iCollapsed == 0 )
        iNumCells = (int) (m_iHigh - m_iLow) + 1;
    else if( m_iCollapsed == 1 )
        iNumCells = 1;
    else
        iNumCells = 0;

    return iNumCells;
}

double CSubRange::GetLow() {
    return m_iLow;
}

double CSubRange::GetHigh( bool* bImplicit ) {
    if( bImplicit != NULL )
        *bImplicit = m_bHighImplicit;

    return m_iHigh;
}

bool CSubRange::GetHighImplicit() {
    return m_bHighImplicit;
}

int  CSubRange::GetCollapsed() {
    return m_iCollapsed;
}



