//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSDeploy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSDeploy.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files to deployment package.
        /// </summary>
        internal static string AddFileOpenTitle {
            get {
                return ResourceManager.GetString("AddFileOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder to deployment package.
        /// </summary>
        internal static string AddFolderFileOpenTitle {
            get {
                return ResourceManager.GetString("AddFolderFileOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files in a deployment package must be on the same disk volume. Please copy all the files onto the same volume and try again..
        /// </summary>
        internal static string ErrorDifferentVolumes {
            get {
                return ResourceManager.GetString("ErrorDifferentVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; not found. The Deployment Specification file may be in the wrong location or the file does not exist..
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL for the server to deploy to.
        /// </summary>
        internal static string ErrorInvalidServerURL {
            get {
                return ResourceManager.GetString("ErrorInvalidServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the package.
        /// </summary>
        internal static string ErrorMissingPackageName {
            get {
                return ResourceManager.GetString("ErrorMissingPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose how to deploy the application.
        /// </summary>
        internal static string ErrorNoDeploymentType {
            get {
                return ResourceManager.GetString("ErrorNoDeploymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one file to the package.
        /// </summary>
        internal static string ErrorNoInputFiles {
            get {
                return ResourceManager.GetString("ErrorNoInputFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid name for the package file.
        /// </summary>
        internal static string ErrorNoOutputFile {
            get {
                return ResourceManager.GetString("ErrorNoOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the folder to deploy the package to.
        /// </summary>
        internal static string ErrorNoOutputFolder {
            get {
                return ResourceManager.GetString("ErrorNoOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code deployment is only supported for CSWeb, Dropbox and FTP.
        /// </summary>
        internal static string ErrorQRCodeNotSupported {
            get {
                return ResourceManager.GetString("ErrorQRCodeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application does not contain any data entry applications. In order to run on a mobile device you must include at least one. Do you want to deploy anyway?.
        /// </summary>
        internal static string NoEntFiles {
            get {
                return ResourceManager.GetString("NoEntFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application does not contain any program information (.pff) files. In order to run on a mobile device you must include at least one. You can create a .pff file by running your application. Are you sure you want to deploy without a .pff file?.
        /// </summary>
        internal static string NoPffFiles {
            get {
                return ResourceManager.GetString("NoPffFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Deployment Package.
        /// </summary>
        internal static string PackageFileSaveTitle {
            get {
                return ResourceManager.GetString("PackageFileSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files (*.bmp, *.jpg, *.png)|*.bmp;*.jpg;*.png.
        /// </summary>
        internal static string QRCodeFileFilter {
            get {
                return ResourceManager.GetString("QRCodeFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save QR Code.
        /// </summary>
        internal static string QRCodeFileSaveTitle {
            get {
                return ResourceManager.GetString("QRCodeFileSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan this QR code on your mobile device to install {0}:.
        /// </summary>
        internal static string QRCodeInstruction {
            get {
                return ResourceManager.GetString("QRCodeInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSPro Deployment Files (*.csds)|*.csds.
        /// </summary>
        internal static string SpecFileFilter {
            get {
                return ResourceManager.GetString("SpecFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Deployment Specification File.
        /// </summary>
        internal static string SpecFileOpenTitle {
            get {
                return ResourceManager.GetString("SpecFileOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Deployment Specification File.
        /// </summary>
        internal static string SpecFileSaveTitle {
            get {
                return ResourceManager.GetString("SpecFileSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Deployed Successfully.
        /// </summary>
        internal static string UploadSuccess {
            get {
                return ResourceManager.GetString("UploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP File (*.zip)|*.zip.
        /// </summary>
        internal static string ZipFileFilter {
            get {
                return ResourceManager.GetString("ZipFileFilter", resourceCulture);
            }
        }
    }
}
