/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_census_cspro_smartsync_http_IStreamWrapper */

#ifndef _Included_gov_census_cspro_smartsync_http_IStreamWrapper
#define _Included_gov_census_cspro_smartsync_http_IStreamWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef gov_census_cspro_smartsync_http_IStreamWrapper_MAX_SKIP_BUFFER_SIZE
#define gov_census_cspro_smartsync_http_IStreamWrapper_MAX_SKIP_BUFFER_SIZE 2048L
/*
 * Class:     gov_census_cspro_smartsync_http_IStreamWrapper
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_census_cspro_smartsync_http_IStreamWrapper_read__
  (JNIEnv *, jobject);

/*
 * Class:     gov_census_cspro_smartsync_http_IStreamWrapper
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_gov_census_cspro_smartsync_http_IStreamWrapper_read___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
