/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_census_cspro_smartsync_SyncListenerWrapper */

#ifndef _Included_gov_census_cspro_smartsync_SyncListenerWrapper
#define _Included_gov_census_cspro_smartsync_SyncListenerWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     gov_census_cspro_smartsync_SyncListenerWrapper
 * Method:    onProgress
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_smartsync_SyncListenerWrapper_onProgress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_smartsync_SyncListenerWrapper
 * Method:    isCancelled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_smartsync_SyncListenerWrapper_isCancelled
  (JNIEnv *, jobject);

JNIEXPORT jboolean JNICALL Java_gov_census_cspro_smartsync_SyncListenerWrapper_isCancelled
    (JNIEnv*, jobject );

JNIEXPORT void JNICALL
Java_gov_census_cspro_smartsync_SyncListenerWrapper_setTotal(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
