/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader */

#ifndef _Included_gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader
#define _Included_gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader
 * Method:    CreateNativeInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader_CreateNativeInstance
  (JNIEnv *, jobject);

/*
 * Class:     gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader
 * Method:    CleanupNativeInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader_CleanupNativeInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader
 * Method:    ConnectToServer
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jint JNICALL Java_gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader_ConnectToServer
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring);

/*
 * Class:     gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader
 * Method:    ListPackages
 * Signature: (JLjava/util/ArrayList;)Z
 */
JNIEXPORT jint JNICALL Java_gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader_ListPackages
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader
 * Method:    InstallPackage
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jint JNICALL Java_gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader_InstallPackage
  (JNIEnv *, jobject, jlong, jstring, jboolean);

JNIEXPORT jint JNICALL
Java_gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader_ListUpdatablePackages(
    JNIEnv *, jobject, jlong, jobject);

JNIEXPORT jint JNICALL
Java_gov_census_cspro_smartsync_addapp_DeploymentPackageDownloader_UpdatePackage(JNIEnv*,
                                                                                 jobject,
                                                                                 jstring,
                                                                                 jstring,
                                                                                 jlong);
#ifdef __cplusplus
}
#endif
#endif
