/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_census_cspro_engine_EngineInterface */

#ifndef _Included_gov_census_cspro_engine_EngineInterface
#define _Included_gov_census_cspro_engine_EngineInterface
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetCurrentPage
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_gov_census_cspro_engine_EngineInterface_GetCurrentPage
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    NextField
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_NextField
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    PrevField
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_PrevField
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    PreviousPersistentField
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_PreviousPersistentField
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GoToField
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_GoToField
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    InsertOcc
 * Signature: (J)V
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_InsertOcc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    DeleteOcc
 * Signature: (J)V
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_DeleteOcc
  (JNIEnv *, jobject, jlong);
/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    InsertOccAfter
 * Signature: (J)V
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_InsertOccAfter
  (JNIEnv *, jobject, jlong);
/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    EndGroup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_EndGroup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    AdvanceToEnd
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_AdvanceToEnd
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    EndLevel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_EndLevel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    EndLevelOcc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_EndLevelOcc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    InitApplication
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_InitApplication
  (JNIEnv *, jobject, jlong applicationReference, jstring);

JNIEXPORT jlong JNICALL Java_gov_census_cspro_engine_EngineInterface_InitNativeEngineInterface
  (JNIEnv *, jobject);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    Start
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_Start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    Stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_Stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    StopCode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_gov_census_cspro_engine_EngineInterface_StopCode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    RunUserTriggedStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_RunUserTriggedStop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    HasPersistentFields
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_HasPersistentFields
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    EndApplication
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_EndApplication
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    ModifyCase
 * Signature: (JD)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_ModifyCase
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    InsertCase
 * Signature: (JLjava/lang/String;D)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_InsertCase
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetSequentialCaseIds
 * Signature: (JLjava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_GetSequentialCaseIds
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    DeleteCase
 * Signature: (JD)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_DeleteCase
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetAskOpIDFlag
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_GetAskOpIDFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetOpIDFromPff
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_engine_EngineInterface_GetOpIDFromPff
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    SetOperatorId
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_SetOperatorId
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetAddLockFlag
 * Signature: (JL)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_GetAddLockFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetModifyLockFlag
 * Signature: (JL)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_GetModifyLockFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetDeleteLockFlag
 * Signature: (JL)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_GetDeleteLockFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetViewLockFlag
 * Signature: (JL)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_GetViewLockFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetCaseListingLockFlag
 * Signature: (JL)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_GetCaseListingLockFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    DoNotShowCaseListing
 * Signature: (JL)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_DoNotShowCaseListing
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    SetAndroidEnvironmentVariables
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_SetAndroidEnvironmentVariables
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetInformationForAbout
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_engine_EngineInterface_GetInformationForAbout
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetSystemControlled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_GetSystemControlled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    ContainsMultipleLanguages
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_ContainsMultipleLanguages
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetStartKeyString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_engine_EngineInterface_GetStartKeyString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetStartPffKey
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_engine_EngineInterface_GetStartPffKey
  (JNIEnv *, jobject, jlong);

JNIEXPORT jobject JNICALL
Java_gov_census_cspro_engine_EngineInterface_QueryPffStartMode(JNIEnv *, jobject,jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    RunUserbarFunction
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_RunUserbarFunction
  (JNIEnv *, jobject, jlong, jint);

/* Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetThreadWaitId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_gov_census_cspro_engine_EngineInterface_GetThreadWaitId
  (JNIEnv *, jobject, jlong);

/* Class:     gov_census_cspro_engine_EngineInterface
 * Method:    SetThreadWaitComplete
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_SetThreadWaitComplete
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    ShowsRefusalsAutomatically
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_ShowsRefusalsAutomatically
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    ShowRefusals
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_ShowRefusals
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    SavePartial
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_SavePartial
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    AllowsPartialSave
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_AllowsPartialSave
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    ChangeLanguage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_ChangeLanguage
  (JNIEnv*, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    EditCaseNote
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_EditCaseNote
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    ReviewNotes
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_ReviewNotes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetAllNotes
 * Signature: (JLjava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_GetAllNotes
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    DeleteNote
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_DeleteNote
  (JNIEnv*, jobject, jlong, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GoToNoteField
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_GoToNoteField
  (JNIEnv*, jobject, jlong, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetCaseTree
 * Signature: (J)Lgov/census/cspro/form/CaseTreeNode;
 */
JNIEXPORT jobject JNICALL Java_gov_census_cspro_engine_EngineInterface_GetCaseTree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    UpdateCaseTree
 * Signature: (J)[Lgov/census/cspro/form/CaseTreeUpdate;
 */
JNIEXPORT jobjectArray JNICALL Java_gov_census_cspro_engine_EngineInterface_UpdateCaseTree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetShowCaseTreeFlag
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_GetShowCaseTreeFlag
  (JNIEnv * pEnv, jobject object, jlong applicationReference);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetAutoAdvanceOnSelectionFlag
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_GetAutoAdvanceOnSelectionFlag
  (JNIEnv * pEnv, jobject object, jlong applicationReference);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetDisplayCodesAlongsideLabelsFlag
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_GetDisplayCodesAlongsideLabelsFlag
  (JNIEnv * pEnv, jobject object, jlong applicationReference);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    OnProgressDialogCancel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_OnProgressDialogCancel
  (JNIEnv * pEnv, jobject object, jlong applicationReference);

/*
* Class:     gov_census_cspro_engine_EngineInterface
* Method:    HasSync
*/
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_HasSync
  (JNIEnv * pEnv, jobject object, jlong applicationReference);

/*
* Class:     gov_census_cspro_engine_EngineInterface
* Method:    SyncApp
*/
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_SyncApp
  (JNIEnv * pEnv, jobject object, jlong applicationReference);

/*
 * Class:     gov_census_cspro_engine_EngineInterface
 * Method:    GetParadataCachedEvents
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_GetParadataCachedEvents
  (JNIEnv* pEnv, jobject object, jlong applicationReference);

/*
* Class:     gov_census_cspro_engine_EngineInterface
* Method:    GetSystemSettingString
*/
JNIEXPORT jstring JNICALL Java_gov_census_cspro_engine_EngineInterface_GetSystemSettingString
  (JNIEnv* pEnv, jobject object, jstring setting_name, jstring default_value);

/*
* Class:     gov_census_cspro_engine_EngineInterface
* Method:    GetSystemSettingBoolean
*/
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_GetSystemSettingBoolean
  (JNIEnv* pEnv, jobject object, jstring setting_name, jboolean default_value);

JNIEXPORT jstring JNICALL Java_gov_census_cspro_engine_EngineInterface_GetRuntimeString
  (JNIEnv* pEnv, jobject object, jint message_number, jstring text);

JNIEXPORT jobject JNICALL Java_gov_census_cspro_engine_EngineInterface_GetMappingOptions
        (JNIEnv* pEnv, jobject object, jlong applicationReference);

JNIEXPORT jobject JNICALL Java_gov_census_cspro_engine_EngineInterface_GetBaseMapSelection
        (JNIEnv* pEnv, jobject object, jlong applicationReference);

JNIEXPORT jstring JNICALL Java_gov_census_cspro_engine_EngineInterface_FormatCoordinates
        (JNIEnv* pEnv, jobject object, jlong applicationReference, jdouble latitude, jdouble longitude);

JNIEXPORT jstring JNICALL Java_gov_census_cspro_engine_EngineInterface_GetApplicationDescription
    (JNIEnv *, jobject, jlong);

JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_RunNonEntryApplication
  (JNIEnv*, jobject, jlong, jstring);

JNIEXPORT jobject JNICALL Java_gov_census_cspro_engine_EngineInterface_RunActionInvoker
  (JNIEnv*, jobject, jlong, jstring, jstring, jstring, jstring, jboolean);

JNIEXPORT jboolean JNICALL Java_gov_census_cspro_engine_EngineInterface_UseHtmlDialogs
  (JNIEnv*, jobject, jlong);

JNIEXPORT jint JNICALL Java_gov_census_cspro_engine_EngineInterface_ParseDimensionText
  (JNIEnv*, jobject, jlong, jstring, jboolean);

JNIEXPORT jstring JNICALL Java_gov_census_cspro_engine_EngineInterface_CreateRegularExpressionFromFileSpec
        (JNIEnv*, jobject, jstring);

JNIEXPORT jobject JNICALL Java_gov_census_cspro_engine_EngineInterface_GetVirtualFile
  (JNIEnv*, jobject, jlong, jstring);

JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_ViewCurrentCase
  (JNIEnv*, jobject, jlong);

JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_ViewCase
  (JNIEnv*, jobject, jlong, jdouble);

JNIEXPORT jint JNICALL Java_gov_census_cspro_engine_EngineInterface_ActionInvokerCreateWebController(JNIEnv*, jobject, jlong, jstring);
JNIEXPORT void JNICALL Java_gov_census_cspro_engine_EngineInterface_ActionInvokerCancelAndWaitOnActionsInProgress(JNIEnv*, jobject, jlong, jint);
JNIEXPORT jstring JNICALL Java_gov_census_cspro_engine_EngineInterface_ActionInvokerProcessMessage(JNIEnv*, jobject, jlong, jint, jobject, jstring, jboolean, jboolean);
JNIEXPORT jstring JNICALL Java_gov_census_cspro_engine_EngineInterface_oldCSProJavaScriptInterfaceGetAccessToken(JNIEnv*, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
