/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_census_cspro_bridge_CNPifFile */

#ifndef _Included_gov_census_cspro_bridge_CNPifFile
#define _Included_gov_census_cspro_bridge_CNPifFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_census_cspro_bridge_CNPifFile
 * Method:    LoadPif
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_census_cspro_bridge_CNPifFile_LoadPif
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gov_census_cspro_bridge_CNPifFile
 * Method:    GetDescription
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_bridge_CNPifFile_GetDescription
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_bridge_CNPifFile
 * Method:    IsAppTypeEntry
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_census_cspro_bridge_CNPifFile_IsAppTypeEntry
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_bridge_CNPifFile
 * Method:    GetShowInApplicationListing
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_gov_census_cspro_bridge_CNPifFile_GetShowInApplicationListing
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_bridge_CNPifFile
 * Method:    GetInputFilename
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_bridge_CNPifFile_GetInputFilename
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_bridge_CNPifFile
 * Method:    GetAppFilename
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_bridge_CNPifFile_GetAppFilename
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_bridge_CNPifFile
 * Method:    ClosePif
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_bridge_CNPifFile_ClosePif
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_bridge_CNPifFile
 * Method:    GetExternalFilenames
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_gov_census_cspro_bridge_CNPifFile_GetExternalFilenames
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_bridge_CNPifFile
 * Method:    GetUserFilenames
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_gov_census_cspro_bridge_CNPifFile_GetUserFilenames
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_bridge_CNPifFile
 * Method:    GetWriteFilename
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_bridge_CNPifFile_GetWriteFilename
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_bridge_CNPifFile
 * Method:    GetOnExitFilename
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_bridge_CNPifFile_GetOnExitFilename
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_bridge_CNPifFile
 * Method:    CreatePffFromIntentExtras
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_bridge_CNPifFile_CreatePffFromIntentExtras
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
