/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_census_cspro_form_EntryPage */

#ifndef _Included_gov_census_cspro_form_EntryPage
#define _Included_gov_census_cspro_form_EntryPage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_census_cspro_form_EntryPage
 * Method:    GetOccurrenceLabel
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_form_EntryPage_GetOccurrenceLabel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_form_EntryPage
 * Method:    GetBlockName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_form_EntryPage_GetBlockName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_form_EntryPage
 * Method:    GetBlockLabel
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_form_EntryPage_GetBlockLabel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_form_EntryPage
 * Method:    GetBlockQuestionTextUrl
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_form_EntryPage_GetBlockQuestionTextUrl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_form_EntryPage
 * Method:    GetBlockHelpTextUrl
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_census_cspro_form_EntryPage_GetBlockHelpTextUrl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_census_cspro_form_EntryPage
 * Method:    GetPageFields
 * Signature: (J)[Lgov/census/cspro/form/CDEField;
 */
JNIEXPORT jobjectArray JNICALL Java_gov_census_cspro_form_EntryPage_GetPageFields
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
