/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_census_cspro_smartsync_http_OStreamWrapper */

#ifndef _Included_gov_census_cspro_smartsync_http_OStreamWrapper
#define _Included_gov_census_cspro_smartsync_http_OStreamWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_census_cspro_smartsync_http_OStreamWrapper
 * Method:    write
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_smartsync_http_OStreamWrapper_write__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gov_census_cspro_smartsync_http_OStreamWrapper
 * Method:    write
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_smartsync_http_OStreamWrapper_write___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     gov_census_cspro_smartsync_http_OStreamWrapper
 * Method:    flush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gov_census_cspro_smartsync_http_OStreamWrapper_flush
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
