JNI_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE            := Engine
LOCAL_C_INCLUDES        := src
CEXENTRY_SRC_PATH       := ../../../../../CEXEntry
ENGINE_SRC_PATH         := ../../../../../engine
ZCAPIO_SRC_PATH         := ../../../../../zCapiO
ZENTRYO_SRC_PATH        := ../../../../../zEntryO
ZISSALIB_SRC_PATH       := ../../../../../zIssaLib

LOCAL_SRC_FILES         += $(CEXENTRY_SRC_PATH)/DeWrite.cpp
LOCAL_SRC_FILES         += $(CEXENTRY_SRC_PATH)/Dicx.cpp
LOCAL_SRC_FILES         += $(CEXENTRY_SRC_PATH)/Entifaz.cpp
LOCAL_SRC_FILES         += $(CEXENTRY_SRC_PATH)/Relation.cpp
LOCAL_SRC_FILES         += $(CEXENTRY_SRC_PATH)/Secx.cpp
LOCAL_SRC_FILES         += $(CEXENTRY_SRC_PATH)/Varx.cpp

LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Applload.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/citer.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Common.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Decorr.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/engdrv.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/EngineExecutor.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Exappl.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Exapplva.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Exopfile.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Form.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/gpsfuncs.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Int_set.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntActionInvoker.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntArray.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntAudio.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntBarcode.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/intcapi.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntCase.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Intchars.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntCompression.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntDataAccess.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntDate.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Intdentr.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntDiagnostics.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntDocument.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Intdrive.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntDynamicLogicEvaluation.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/intenter.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/InterpreterAccessor.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Intexpr.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Intextdi.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntFreq.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Intfuncs.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntGeometry.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntHashMap.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntHtmlDialog.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntImage.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntImpute.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Intinstr.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntItem.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntJson.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntLanguage.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntList.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntLocalhost.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntMap.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntMath.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntMessages.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntOccurrences.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntPath.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntPff.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntPre77Report.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntProgramControl.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntProperties.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntQuery.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntReport.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntString.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntSwitch.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntSymbol.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntSync.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntSystemApp.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntUserbar.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntUserFunction.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntUserInterface.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntValues.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/IntVariable.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Issafunc.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Listing.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/LoadSaveBinary.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Messages.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Nextnode.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/ParadataDriver.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/ParameterManager.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Pre80Routines.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/QuestionTextParamCache.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/relt.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Settings.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/subtable.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/SyncListener.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Tables.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/Tablesen.cpp
LOCAL_SRC_FILES         += $(ENGINE_SRC_PATH)/VariableInOut.cpp

LOCAL_SRC_FILES         += $(ZCAPIO_SRC_PATH)/Capi.cpp
LOCAL_SRC_FILES         += $(ZCAPIO_SRC_PATH)/CapiCondition.cpp
LOCAL_SRC_FILES         += $(ZCAPIO_SRC_PATH)/CapiFill.cpp
LOCAL_SRC_FILES         += $(ZCAPIO_SRC_PATH)/CapiQuestion.cpp
LOCAL_SRC_FILES         += $(ZCAPIO_SRC_PATH)/CapiQuestionFilePre76.cpp
LOCAL_SRC_FILES         += $(ZCAPIO_SRC_PATH)/CapiQuestionManager.cpp
LOCAL_SRC_FILES         += $(ZCAPIO_SRC_PATH)/CapiQuestionYaml.cpp
LOCAL_SRC_FILES         += $(ZCAPIO_SRC_PATH)/CapiStyle.cpp
LOCAL_SRC_FILES         += $(ZCAPIO_SRC_PATH)/CapiText.cpp

LOCAL_SRC_FILES         += $(ZENTRYO_SRC_PATH)/CapiContentVirtualFileMapping.cpp
LOCAL_SRC_FILES         += $(ZENTRYO_SRC_PATH)/CaseTreeBuilder.cpp
LOCAL_SRC_FILES         += $(ZENTRYO_SRC_PATH)/CaseTreeNode.cpp
LOCAL_SRC_FILES         += $(ZENTRYO_SRC_PATH)/CaseTreeUpdate.cpp
LOCAL_SRC_FILES         += $(ZENTRYO_SRC_PATH)/CoreEntryEngineInterface.cpp
LOCAL_SRC_FILES         += $(ZENTRYO_SRC_PATH)/CoreEntryPage.cpp
LOCAL_SRC_FILES         += $(ZENTRYO_SRC_PATH)/CoreEntryPageField.cpp
LOCAL_SRC_FILES         += $(ZENTRYO_SRC_PATH)/DeploymentPackageDownloader.cpp
LOCAL_SRC_FILES         += $(ZENTRYO_SRC_PATH)/EntDrv.cpp
LOCAL_SRC_FILES         += $(ZENTRYO_SRC_PATH)/LevelNodeProcessing.cpp
LOCAL_SRC_FILES         += $(ZENTRYO_SRC_PATH)/RunAple.cpp
LOCAL_SRC_FILES         += $(ZENTRYO_SRC_PATH)/WEXEntry.cpp

LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/Attr.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/CFlAdmin.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/CFlow.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/CsDriver.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/CsDriver1.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/CsKernel.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/Defuncs.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/Dict.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/Dictload.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/EngineAccessor.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/EngineLoader.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/Exallocd.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/Exapplfu.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/Exapplin.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/ExNotes.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/FlowCore.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/FlowLoad.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/Form2.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/GroupT.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/GroupT2.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/GroupVisitor.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/Labsalo.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/OccurrenceInfo.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/OccurrenceInfoSet.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/OccurrenceVisitor.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/SecT.cpp
LOCAL_SRC_FILES         += $(ZISSALIB_SRC_PATH)/VarT.cpp

LOCAL_CFLAGS            += -DANDROID=1
LOCAL_CFLAGS            += -DUNICODE=1
LOCAL_CFLAGS            += -D_UNICODE=1
LOCAL_CFLAGS            += -DGENERATE_BINARY=1
LOCAL_CFLAGS            += -DUSE_BINARY=1
LOCAL_C_INCLUDES        += $(JNI_PATH)/../../../../../external
LOCAL_C_INCLUDES        += $(JNI_PATH)/../../../../../external/geometry.hpp/include
LOCAL_C_INCLUDES        += $(JNI_PATH)/../../../../../external/jsoncons
LOCAL_C_INCLUDES        += $(JNI_PATH)/../../../../../external/variant/include
LOCAL_C_INCLUDES        += $(JNI_PATH)/../../../../../external/yaml-cpp/include
LOCAL_STATIC_LIBRARIES  := zEngineF zEngineO zAction zLogicO zFormatterO zFormO zSyncO zDiffO zReformatO zIndexO zConcatO zSortO zPackO zDataO zCaseO zMultimediaO zMapping zMessageO zReportO zFreqO zParadataO zZipO zDictO zAppO zUtilO zUtilF zHtml zListingO zJson zToolsO zPlatformO SQLite rtf2html yamlcpp

include $(BUILD_STATIC_LIBRARY)
