include $(CLEAR_VARS)

LOCAL_MODULE            := zEngineO
ZENGINEO_SRC_PATH       := ../../../../../zEngineO

LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Audio.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Array.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/BinarySymbol.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/BinarySymbolData.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Block.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Document.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/EngineCase.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/EngineData.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/EngineDataRepository.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/EngineDictionary.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/EngineItem.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/EngineRecord.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/File.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Flow.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Geometry.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/HashMap.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Image.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Imputation.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/List.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/LogicByteCode.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/LoopStack.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Map.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/NamedFrequency.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/PenReaderApplicationLoader.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/PersistentVariableProcessor.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Pff.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/PffExecutor.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/PreinitializedVariable.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/ProcType.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Report.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/ReportTokenizer.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/ResponseProcessor.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/RunnableSymbol.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/RuntimeEvent.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/SaveArrayFile.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/SymbolCalculator.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/SystemApp.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/UserFunction.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/UserFunctionArgumentChecker.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/UserFunctionLocalSymbolsManager.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/ValueSet.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Versioning.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/WorkString.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/WorkVariable.cpp

LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/ActionInvokerCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/ArgumentSpecificationCompiler.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/ArrayCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/AudioCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/BarcodeCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/CaseCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/CompilerHelper.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/ControlFlowCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/DataAccessCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/DictionaryCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/DocumentCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/EngineDictionaryCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/ExpressionsCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/FileCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/FreqCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/FunctionsGenericCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/FunctionsVariousCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/GeometryCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/GpsCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/HashMapCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/ImageCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/ImputeCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/ItemCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/JsonCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/ListCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/LogicCompiler.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/MapCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/MessagesCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/NextTokenCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/NodeCreationCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/NumbersCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/OptionalNamedArgumentsCompiler.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/PathCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/PffCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/QueryCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/ReportCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/StringsCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/SwitchCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/SymbolsCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/SyncCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/SystemAppCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/TokenCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/TraceCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/UserbarCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/UserFunctionCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/UserInterfaceCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/ValueSetCC.cpp
LOCAL_SRC_FILES         += $(ZENGINEO_SRC_PATH)/Compiler/VariableCC.cpp

LOCAL_CFLAGS            += -DANDROID=1
LOCAL_CFLAGS            += -DUNICODE=1
LOCAL_CFLAGS            += -D_UNICODE=1
LOCAL_C_INCLUDES        += $(JNI_PATH)/../../../../../zEngineO
LOCAL_C_INCLUDES        += $(JNI_PATH)/../../../../../external/geometry.hpp/include
LOCAL_C_INCLUDES        += $(JNI_PATH)/../../../../../external/variant/include

LOCAL_STATIC_LIBRARIES  := zLogicO zAppO zCaseO zConcatO zDataO zDictO zDiffO zFreqO zFormO zIndexO zMapping zMessageO zMultimediaO zPackO zParadataO zReformatO zSortO zUtilF zHtml zUtilO zJson zToolsO zPlatformO 

include $(BUILD_STATIC_LIBRARY)
