//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by zFormF.rc
//
#define IDR_BOXTOOLBAR                  8001
#define IDR_COND_ACCELERATOR            8002
#define IDR_QSFBAR                      8003
#define IDD_BLOCKPROP                   8004
#define IDD_COLUMNPROP                  8005
#define IDD_DATA_SOURCE_OPTIONS_DLG     8006
#define IDD_DE_OPTIONS                  8007
#define IDD_DRAG_OPTS                   8008
#define IDD_FFPROP                      8009
#define IDD_FIELD_COLORS_DLG            8010
#define IDD_FIELD_FONT_DLG              8011
#define IDD_FIELDPROP                   8012
#define IDD_FORMPROP                    8013
#define IDD_GLOBALFONTDLG               8014
#define IDD_GRIDBOXPROP                 8015
#define IDD_GRIDPROP                    8016
#define IDD_GRIDTEXTPROP                8017
#define IDD_JOIN                        8018
#define IDD_KEYBOARD_LAYOUTS            8019
#define IDD_LEVELPROP                   8020
#define IDD_MAPPING_OPTIONS             8021
#define IDD_MULTIPLE_FIELD_PROP         8022
#define IDD_QSF_EDIT_VIEW               8023
#define IDD_QSFSTYLEDLG                 8024
#define IDD_ROWPROP                     8025
#define IDD_RUNASB_DLG                  8026
#define IDD_SYNC_PARAMS_DIALOG          8027
#define IDD_TEXT_PROPDLG                8028
#define IDD_TEXTFONTDLG                 8029
#define IDI_FORMFILE                    8030
#define IDI_FORMFILE_LOGIC              8031
#define IDI_LEVEL                       8032
#define IDI_LEVEL_LOGIC                 8033
#define IDI_FORM                        8034
#define IDI_FORM_LOGIC                  8035
#define IDI_FORM_LOOPING                8036
#define IDI_FORM_LOOPING_LOGIC          8037
#define IDI_ROSTER                      8038
#define IDI_ROSTER_LOGIC                8039
#define IDI_FIELD                       8040
#define IDI_FIELD_LOGIC                 8041
#define IDI_FIELD_QUESTION              8042
#define IDI_FIELD_LOGIC_QUESTION        8043
#define IDI_PROTECTED                   8044
#define IDI_PROTECTED_LOGIC             8045
#define IDI_MIRROR                      8046
#define IDI_MIRROR_LOGIC                8047
#define IDI_CAPTURE_ERROR               8048
#define IDB_COL_ORIENT                  8049
#define IDB_ROW_ORIENT                  8050
#define IDS_CUSTOMFONT                  8051
#define IDS_DEFAULTFONT                 8052
#define IDS_GRIDTEXTMSG1                8053
#define IDS_GRIDTEXTMSG2                8054
#define IDS_GRIDTEXTMSG3                8055
#define IDS_SYSTEMFONT                  8056
#define IDC_ADD_STYLE                   8500
#define IDC_ALIGNHORZ                   8501
#define IDC_ALIGNVERT                   8502
#define IDC_ALLOW_DELETE_OTHER_OPERATOR_NOTES 8503
#define IDC_ALLOW_EDIT_OTHER_OPERATOR_NOTES 8504
#define IDC_ALLOW_PART_SAVE             8505
#define IDC_ALWAYS_VISUAL_VALUE         8506
#define IDC_APPLY                       8507
#define IDC_APPLY_TO_ALL_FIELDS         8508
#define IDC_APPLY_TO_SELECTED_FIELDS    8509
#define IDC_ASKOPID                     8510
#define IDC_AUTO_ADVANCE                8511
#define IDC_AUTO_PARTIAL_SAVE           8512
#define IDC_AUTO_PARTIAL_SAVE_MINUTES   8513
#define IDC_AUTOINCREMENT               8514
#define IDC_CAPTURE                     8515
#define IDC_CAPTURE_DESCRIPTION         8516
#define IDC_CAPTURE_ERROR_ICON          8517
#define IDC_CAPTURE_ERROR_TEXT          8518
#define IDC_CAPTURE_TYPE                8519
#define IDC_CAPTURE_TYPES_CAPI          8520
#define IDC_CAPTURE_TYPES_PAPI          8521
#define IDC_CAPTURETYPE                 8522
#define IDC_CENTERFORMS                 8523
#define IDC_CHANGE_KEYBOARD             8524
#define IDC_CHECK_SHOW_SAME_SCREEN      8525
#define IDC_CHECKBOX_ENABLE_SYNC        8526
#define IDC_CHECKRANGES                 8527
#define IDC_COLOR                       8528
#define IDC_COMBO                       8529
#define IDC_COMBO_CASE_TREE             8530
#define IDC_COMBO_COLOR                 8531
#define IDC_COMBO_DIRECTION             8532
#define IDC_COMBO_FONT                  8533
#define IDC_COMBO_FONT_SIZE             8534
#define IDC_COMBO_FONT_STYLE            8535
#define IDC_COMBO_LATITUDE              8536
#define IDC_COMBO_LONGITUDE             8537
#define IDC_COMMADECIMAL                8538
#define IDC_CREATE_LISTING_FILE         8539
#define IDC_CREATE_LOG_FILE             8540
#define IDC_CSWEB                       8541
#define IDC_DATE_FORMAT                 8542
#define IDC_DELETE_STYLE                8543
#define IDC_DELETE_STYLE_DISABLED       8544
#define IDC_DISPLAY_CODES_WITH_LABELS   8545
#define IDC_DROPBOX                     8546
#define IDC_EDIT_LANG                   8547
#define IDC_EDIT_URL                    8548
#define IDC_ENABLE_MAPPING_CASE_LIST    8549
#define IDC_ENTERKEY                    8550
#define IDC_FF_LABEL                    8551
#define IDC_FF_NAME                     8552
#define IDC_FIELD_COLORS_RESET          8553
#define IDC_FIELD_COLORS_UNVISITED      8554
#define IDC_FIELD_COLORS_VISITED        8555
#define IDC_FIELD_COLORS_CURRENT        8556
#define IDC_FIELD_COLORS_SKIPPED        8557
#define IDC_FIELD_FONT                  8558
#define IDC_FIELD_FONT_DESC             8559
#define IDC_FIELD_RESET                 8560
#define IDC_FLDNAME                     8561
#define IDC_FLDTXT                      8562
#define IDC_FONT                        8563
#define IDC_FONTDESC                    8564
#define IDC_FONTFACE                    8565
#define IDC_FONTRADIO1                  8566
#define IDC_FONTRADIO2                  8567
#define IDC_FONTSIZE                    8568
#define IDC_FORM_LABEL                  8569
#define IDC_FORM_NAME                   8570
#define IDC_FREEMOVE                    8571
#define IDC_FREQ                        8572
#define IDC_FTP                         8573
#define IDC_GRID_HORZ                   8574
#define IDC_GRID_LABEL                  8575
#define IDC_GRID_NAME                   8576
#define IDC_GRID_VERT                   8577
#define IDC_GRIDBOXMSG1                 8578
#define IDC_GRIDBOXRADIO1               8579
#define IDC_GRIDBOXRADIO2               8580
#define IDC_GRIDTEXTMSG1                8581
#define IDC_GRIDTEXTRADIO1              8582
#define IDC_GRIDTEXTRADIO2              8583
#define IDC_GROUP_LABEL                 8584
#define IDC_GROUP_NAME                  8585
#define IDC_HIDE_IN_CASETREE            8586
#define IDC_HORZ                        8587
#define IDC_HORZM                       8588
#define IDC_HTML_EDIT                   8589
#define IDC_INPUTTYPE                   8590
#define IDC_JOIN_MSG                    8591
#define IDC_JOIN_TEXT                   8592
#define IDC_KEYBOARD_DESC               8593
#define IDC_KEYBOARD_LIST               8594
#define IDC_KEYBOARDINPUT               8595
#define IDC_LABEL                       8596
#define IDC_LEVEL_LABEL                 8597
#define IDC_LEVEL_NAME                  8598
#define IDC_LINK_LABELS                 8599
#define IDC_LINKED_TO_DICT              8600
#define IDC_LIST_STYLES                 8601
#define IDC_MAXOCCFLD                   8602
#define IDC_MIRROR                      8603
#define IDC_MULT_HIDE_IN_CASETREE       8604
#define IDC_PATH_OFF                    8605
#define IDC_PATH_ON                     8606
#define IDC_PERSISTENT                  8607
#define IDC_PROTECTED                   8608
#define IDC_RADIOFONT                   8609
#define IDC_RADIOFONT2                  8610
#define IDC_REQUIRE_ENTER               8611
#define IDC_RESET                       8612
#define IDC_RNDSTART                    8613
#define IDC_ROSTER_HORIZONTAL           8614
#define IDC_ROSTER_VERTICAL             8615
#define IDC_ROSTER_NONE                 8616
#define IDC_ROWCOL_EDIT                 8617
#define IDC_ROWCOL_TEXT                 8618
#define IDC_RTLROSTERS                  8619
#define IDC_SAMPLE                      8620
#define IDC_SCREEN_TEXT                 8621
#define IDC_SEQUENTIAL                  8622
#define IDC_SETCAPTUREPOS_APPLY         8623
#define IDC_SETCAPTUREPOS_CHECK         8624
#define IDC_SETCAPTUREPOS_DISABLE       8625
#define IDC_SETCAPTUREPOS_X             8626
#define IDC_SETCAPTUREPOS_Y             8627
#define IDC_SHOW_ERROR_MESSAGE_NUMBERS  8628
#define IDC_SHOW_FIELD_LABELS           8629
#define IDC_SHOW_ONLY_DISCRETE_IN_COMBO 8630
#define IDC_SHOWENDCASE                 8631
#define IDC_SHOWREFUSALS                8632
#define IDC_SKIPSTRUC                   8633
#define IDC_SKIPTO                      8634
#define IDC_SPINFREQ                    8635
#define IDC_SPINSTART                   8636
#define IDC_STARTVER                    8637
#define IDC_STATIC_DATE_FORMAT          8638
#define IDC_STATIC_URL                  8639
#define IDC_STYLE                       8640
#define IDC_STYLE_NAME                  8641
#define IDC_SYSTEM_FONT_DESC            8642
#define IDC_TEST                        8643
#define IDC_TEST_CONNECTION             8644
#define IDC_TEXT                        8645
#define IDC_TEXT_LEFT                   8646
#define IDC_TEXT_RIGHT                  8647
#define IDC_TEXTSTATIC                  8648
#define IDC_TXT                         8649
#define IDC_UNDERLINE                   8650
#define IDC_UPPERCASE                   8651
#define IDC_USE_OCCURRENCE_LABELS       8652
#define IDC_USE_QUESTION_TEXT           8653
#define IDC_USE_SUBITEMS                8654
#define IDC_USELABELS                   8655
#define IDC_USENAMES                    8656
#define IDC_VALIDATION_METHOD           8657
#define IDC_VERIFY                      8658
#define IDC_VERT                        8659
#define IDC_VERTM                       8660
#define ID_ADD_BLOCK                    44001
#define ID_ADD_FORM                     44002
#define ID_ADD_TEXT                     44003
#define ID_ADDCAPI_LANG                 44004
#define ID_CAPI_MACROS                  44005
#define ID_COMPILE                      44006
#define ID_DELETE_COLUMN                44007
#define ID_DELETE_FORM                  44008
#define ID_DELETE_ITEM                  44009
#define ID_DUPLICATE_LINE               44010
#define ID_EDIT_BLOCKPROP               44011
#define ID_EDIT_BOXPROP                 44012
#define ID_EDIT_CAPI_STYLES             44013
#define ID_EDIT_CELLPROP                44014
#define ID_EDIT_COLUMNPROP              44015
#define ID_EDIT_COPYF                   44016
#define ID_EDIT_DEL                     44017
#define ID_EDIT_DRAGOPTS                44018
#define ID_EDIT_FFPROP                  44019
#define ID_EDIT_FIELDPROP               44020
#define ID_EDIT_FORMPROP                44021
#define ID_EDIT_GRID_AUTOFIT            44022
#define ID_EDIT_GRIDPROP                44023
#define ID_EDIT_INS                     44024
#define ID_EDIT_INSERT_IMAGE            44025
#define ID_EDIT_JOIN                    44026
#define ID_EDIT_LEVELPROP               44027
#define ID_EDIT_MULTIPLE_FIELDPROP      44028
#define ID_EDIT_OPTIONS                 44029
#define ID_EDIT_PASTE_WITHOUT_FORMATTING 44030
#define ID_EDIT_PASTEF                  44031
#define ID_EDIT_SPLIT                   44032
#define ID_EDIT_STUBPROP                44033
#define ID_EDIT_TEXTPROP                44034
#define ID_FIELDCOLORS                  44035
#define ID_FIELDFONT                    44036
#define ID_FILE_GENERATEBINARY          44037
#define ID_FILE_PUBLISHANDDEPLOY        44038
#define ID_FIND_NEXT                    44039
#define ID_FORM_TOOLBAR                 44040
#define ID_FORMAT_ALIGNCENTER           44041
#define ID_FORMAT_ALIGNLEFT             44042
#define ID_FORMAT_ALIGNRIGHT            44043
#define ID_FORMAT_BOLD                  44044
#define ID_FORMAT_COLOR                 44045
#define ID_FORMAT_ITALIC                44046
#define ID_FORMAT_OUTLINE_BULLET        44047
#define ID_FORMAT_OUTLINE_NUM           44048
#define ID_FORMAT_OUTLINE_NUMBER        44049
#define ID_FORMAT_UNDERLINE             44050
#define ID_FRM_EDIT_FIND                44051
#define ID_GENERATE_FRM                 44052
#define ID_GLOBALFONT                   44053
#define ID_GO                           44054
#define ID_GRIDREFRESH                  44055
#define ID_INSERT_LINK                  44056
#define ID_INSERT_TABLE                 44057
#define ID_LAYOUT_ALIGN_LEFT            44058
#define ID_LAYOUT_ALIGN_RIGHT           44059
#define ID_LAYOUT_ALIGN_TOP             44060
#define ID_LAYOUT_ALIGN_BOTTOM          44061
#define ID_LAYOUT_HORIZONTALLY_CENTER   44062
#define ID_LAYOUT_HORIZONTALLY_SPACE_EVENLY 44063
#define ID_LAYOUT_VERTICALLY_SPACE_EVENLY 44064
#define ID_LAYOUT_VERTICALLY_CENTER     44065
#define ID_OPTIONS_DATA_SOURCES         44066
#define ID_OPTIONS_FIELD_PROPERTIES     44067
#define ID_OPTIONS_MAPPING              44068
#define ID_OPTIONS_SYNCHRONIZATION      44069
#define ID_PROPERTIES                   44070
#define ID_QSF_EDITOR                   44071
#define ID_QSF_EDITOR_VIEW_CODE         44072
#define ID_QSFCOND_ADD                  44073
#define ID_QSFCOND_DELETE               44074
#define ID_QSFCOND_INSERT               44075
#define ID_QSFCOND_MODIFY               44076
#define ID_REPLACE                      44077
#define ID_RUNAS_BCH                    44078
#define ID_SELECT_ITEMS                 44079
#define ID_SELITEMS_FROMTB              44080
#define ID_DRAW_ETCHED                  44081
#define ID_DRAW_RAISED                  44082
#define ID_DRAW_THINBOX                 44083
#define ID_DRAW_THICKBOX                44084
#define ID_SHOW_BOXTOOLBAR              44085
#define ID_TEXT_DIR_LTR                 44086
#define ID_TEXT_DIR_RTL                 44087
#define ID_TOGGLE_QN                    44088
#define ID_UNGROUP                      44089
#define ID_UNGROUP_ITEMS                44090
#define ID_VIEW_FORM                    44091
#define ID_VIEW_GOTO_LOGIC_WORD         44092
#define ID_VIEW_HIDE                    44093
#define ID_VIEW_PEEK_LOGIC_WORD         44094
#define ID_VQSF_EDITOR                  44095
#define ID_VVIEW_LOGIC                  44096

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8057
#define _APS_NEXT_COMMAND_VALUE         44097
#define _APS_NEXT_CONTROL_VALUE         8661
#define _APS_NEXT_SYMED_VALUE           8057
#endif
#endif
