#pragma once
//---------------------------------------------------------------------------
//  File name: SubRange.h
//
//  Description:
//          Header for CSubRange class
//          This class define a subrange from a crosstab coordinate
//
//  History:    Date       Author   Comment
//              ---------------------------
//              30 Jul 01   RHF     Created
//
//---------------------------------------------------------------------------

#include <ZTBDO/zTbdO.h>
#include <ZTBDO/cttree.h>

class CLASS_DECL_ZTBDO CSubRange {
private:
    double       m_iLow;
    double       m_iHigh;
    bool        m_bHighImplicit;

    // 0 if this range generate m_iHigh-m_iLow cells
    // 1 to n if this range is collapsed with others.
    int         m_iCollapsed;

public:
    CSubRange();

    CSubRange( double iLow, double iHigh, bool bHighImplicit, int iCollapsed=0 );

    void    Init( double iLow, double iHigh, bool bHighImplicit, int iCollapsed=0 );

    int     GetNumCells();// Number of cells generated by this range. If the range is collapsed then only the first range generate 1 cell
    double   GetLow();
    double   GetHigh( bool* bImplicit=NULL );

    bool    GetHighImplicit();
    int     GetCollapsed();
};
