#pragma once

#include <zToolsO/CSProException.h>


// Errors generated by sync functions
struct SyncException : public CSProException
{
    explicit SyncException(const CString& msg)
        : CSProException(msg)
    {}
};

struct SyncError : public SyncException
{
    explicit SyncError(int errorCode, const CString& msg)
        : SyncException(msg),
          m_errorCode(errorCode)
    {}

    explicit SyncError(int errorCode)
        : SyncException(_T("Sync error")),
          m_errorCode(errorCode)
    {}

    const int m_errorCode;
};

struct SyncCancelException : public SyncException
{
    explicit SyncCancelException()
        : SyncException(_T("Sync canceled"))
    {}
};

struct SyncRetryableNetworkError : public SyncError
{
    explicit SyncRetryableNetworkError(int errorCode, const CString& msg)
        : SyncError(errorCode, msg)
    {
    }
};

struct SyncLoginDeniedError : public SyncError
{
    explicit SyncLoginDeniedError(int errorCode)
        : SyncError(errorCode)
    {}
};

struct SQLiteError : public SyncError
{
    explicit SQLiteError(int errorCode)
        : SyncError(errorCode)
    {
    }
};
