//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CSPro.rc
//
#define IDR_APLTYPE                     101
#define IDR_MAINFRAME                   102
#define IDI_QSF_FILE                    103
#define IDI_XTS_FILE                    104
#define IDI_BCH_FILE                    105
#define IDI_XTB_FILE                    106
#define IDI_ICON_FILLER06               107
#define IDI_FILE_OPEN                   108
#define IDI_FILE_NEW                    109
#define IDI_DCF_FILE                    110
#define IDI_FRM_FILE                    111
#define IDI_ORD_FILE                    112
#define IDI_ENT_FILE                    113
#define IDI_MGF_FILE                    114
#define IDI_ENT_FILE_CAPI               115
#define IDI_ICON_FILLER01               116
#define IDI_ICON_FILLER02               117
#define IDI_ICON_FILLER03               118
#define IDI_ICON_FILLER04               119
#define IDI_ICON_FILLER05               120
#define IDI_ENC_FILE                    121
#define IDI_RESOURCE_FOLDER             122
#define IDI_CSDBE_FILE                  123
#define IDI_ENT_FILE_OPERATIONAL_CONTROL 124
#define IDI_ENT_FILE_ALL_TYPES          125
#define IDR_MEASURTYPE                  126
#define IDD_APLFILEASSOCIATIONSDLG      127
#define IDD_CAPI_MACROS                 128
#define IDD_COMMON_STORE                129
#define IDD_DIALOGBAR                   130
#define IDD_DICTTYPE                    131
#define IDD_FONTPREFDLG                 132
#define IDD_NEW_ABOUT                   133
#define IDD_NEW_FILE                    134
#define IDD_ONKEY_CHAR_MAP              135
#define IDD_PROPERTIES                  136
#define IDD_PROPERTIES_ADVANCED_FEATURES 137
#define IDD_PROPERTIES_CSPROPS_FILE     138
#define IDD_PROPERTIES_JSON             139
#define IDD_PROPERTIES_MAPPING          140
#define IDD_PROPERTIES_MAPPING_TILE_PROVIDER 141
#define IDD_PROPERTIES_PARADATA         142
#define IDD_REPORT_PROPERTIES           143
#define IDD_SELECT_APP                  144
#define IDD_SELECT_DOCS                 145
#define IDD_START                       146
#define IDD_SYMBOL_ANALYSIS             147
#define IDD_TROUBLESHOOTING             148
#define IDD_VERSION_SHIFTER             149
#define IDB_ABOUT_LOGO                  150
#define IDS_APPMODIFIED                 151
#define IDS_CANT_RENAME_DICT_IN_FORM    152
#define IDS_FILEOPEN                    153
#define IDS_INVLDAPPTYPE                154
#define IDS_LOGIC_ALREADY_IN_APP        155
#define IDS_MESSAGE_ALREADY_IN_APP      156
#define IDS_OPENAPPFLD                  157
#define IDS_OVERWRITE_FILE              158
#define IDS_OVERWRITE_OPEN_FILE         159
#define IDS_RESOURCE_FOLDER_ALREADY_IN_APP 160
#define IDS_RESOURCE_FOLDER_INVALID     161
#define IDS_SAVE_AS_SAVE_ERROR          162
#define IDC_ACCESS_TOKEN                1000
#define IDC_ACCESS_TOKEN_TEXT           1001
#define IDC_APPLICATION_FILENAME        1002
#define IDC_APPLIST                     1003
#define IDC_BASE_MAP                    1004
#define IDC_BUTTON_COMMON_STORE_DELETE  1005
#define IDC_BUTTON_COMMON_STORE_MODIFY  1006
#define IDC_CAPI_AUDIT_UNDEFINED_TEXT   1007
#define IDC_CAPI_INCLUDE_BLOCKS         1008
#define IDC_CAPI_INCLUDE_PROTECTED_FIELDS 1009
#define IDC_CAPI_INITIALIZE_FROM_DICTIONARY_LABEL 1010
#define IDC_CAPI_REMOVE_UNUSED_TEXT     1011
#define IDC_COMBO_COMMON_STORE_TYPE     1012
#define IDC_COORDINATE_DISPLAY_EXAMPLE  1013
#define IDC_CREATE_NEW                  1014
#define IDC_CSPROPS_FILENAME            1015
#define IDC_DECIMAL                     1016
#define IDC_DICTTREE                    1017
#define IDC_DICTTYPE                    1018
#define IDC_DMS                         1019
#define IDC_DOCS_LIST                   1020
#define IDC_EDIT_COMMON_STORE_ATTRIBUTE 1021
#define IDC_EDIT_COMMON_STORE_VALUE     1022
#define IDC_ELIGIBLE_VERSIONS           1023
#define IDC_ESRI                        1024
#define IDC_FILE                        1025
#define IDC_FILE_LIST                   1026
#define IDC_FILE_NEW                    1027
#define IDC_FILE_OPEN                   1028
#define IDC_FONT_CMB                    1029
#define IDC_FORMTREE                    1030
#define IDC_JSON_ARRAY                  1031
#define IDC_JSON_BINARY_CONTENT         1032
#define IDC_JSON_FORMAT                 1033
#define IDC_JSON_HASHMAP                1034
#define IDC_LIST_COMMON_STORE           1035
#define IDC_MAPBOX                      1036
#define IDC_MEASURETAB                  1037
#define IDC_NEW_FILE_CATEGORIES         1038
#define IDC_NEW_FILE_DESCRIPTION        1039
#define IDC_NEW_FILE_TYPES              1040
#define IDC_NEWGRID                     1041
#define IDC_OBJTREE                     1042
#define IDC_ONKEY_ALT                   1043
#define IDC_ONKEY_CHAR                  1044
#define IDC_ONKEY_CODE                  1045
#define IDC_ONKEY_CONTROL               1046
#define IDC_ONKEY_SHIFT                 1047
#define IDC_ONKEY_UNICODE_CHAR          1048
#define IDC_ONKEY_UNICODE_CODE          1049
#define IDC_OPEN_EXISTING               1050
#define IDC_ORDERTREE                   1051
#define IDC_PARADATA_DEVICE_STATE_MINUTES 1052
#define IDC_PARADATA_EVENTS             1053
#define IDC_PARADATA_EVENTS_ALL         1054
#define IDC_PARADATA_EVENTS_SOME        1055
#define IDC_PARADATA_EVENTS_NO          1056
#define IDC_PARADATA_GPS_LOCATION_MINUTES 1057
#define IDC_PARADATA_RECORD_COORDINATES 1058
#define IDC_PARADATA_RECORD_ENTERED_VALUES 1059
#define IDC_PARADATA_RECORD_INITIAL_PROPERTY_VALUES 1060
#define IDC_PARADATA_RECORD_ITERATOR_LOAD_CASES 1061
#define IDC_PASTE_FROM_CLIPBOARD        1062
#define IDC_PREVIEW_MAP                 1063
#define IDC_RADIO_COMMON_STORE_ADD      1064
#define IDC_RADIO_COMMON_STORE_MODIFY   1065
#define IDC_RADIOEXT                    1066
#define IDC_RADIOOUTPUT                 1067
#define IDC_RADIOWKG                    1068
#define IDC_REPORT_FILENAME             1069
#define IDC_REPORT_NAME                 1070
#define IDC_RESET_BTN                   1071
#define IDC_RESET_PROPERTIES            1072
#define IDC_SAVE_PROPERTIES_TO_APPLICATION 1073
#define IDC_SAVE_PROPERTIES_TO_CSPROPS  1074
#define IDC_SELECT_CSPROPS_FILE         1075
#define IDC_SELECT_OFFLINE_MAP          1076
#define IDC_SELECTALL                   1077
#define IDC_SYMBOL_ANALYSIS_CONTEXT     1078
#define IDC_SYMBOL_ANALYSIS_SYMBOLS_LABEL 1079
#define IDC_SYMBOL_ANALYSIS_TREE        1080
#define IDC_SYMBOL_ANALYSIS_USES        1081
#define IDC_SYMBOL_ANALYSIS_USES_LABEL  1082
#define IDC_TABLETREE                   1083
#define IDC_TILE_LAYERS                 1084
#define IDC_TROUBLESHOOTING_CSPROUSERS  1085
#define IDC_TROUBLESHOOTING_EMAIL       1086
#define IDC_TROUBLESHOOTING_PACK        1087
#define IDC_TROUBLESHOOTING_WEBSITE     1088
#define IDC_USE_COMPONENTS_INSTEAD_OF_NATIVE_VERSIONS 1089
#define IDC_USE_HTML_DIALOGS            1090
#define IDC_WORKING                     1091
#define IDC_ZOOMCMB                     1092
#define ID_ABOUT1                       40001
#define ID_CHANGE_TAB                   40002
#define ID_DICTTYPE                     40003
#define ID_OBJDICTTYPE                  40004
#define ID_PREFERENCES_FONTS            40005
#define ID_STATUS_PANE_INDICATOR        40006
#define ID_TOOLS_VERSION_SHIFTER        40007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         40008
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           163
#endif
#endif
