#pragma once

#pragma warning(disable:4800)
#pragma warning(disable:4996)

#include <engine/StandardSystemIncludes.h>

#include <zToolsO/Encoders.h>
#include <zToolsO/SharedSettings.h>
#include <zToolsO/WinClipboard.h>
#include <zUtilO/CSProExecutables.h>
#include <zUtilO/Filedlg.h>
#include <zUtilO/imsaStr.h>
#include <zUtilO/Interapp.h>
#include <zUtilO/StdioFileUnicode.h>
#include <zUtilO/Specfile.h>
#include <zUtilO/TextSourceEditable.h>
#include <zUtilO/TextSourceExternal.h>
#include <zUtilO/Viewers.h>
#include <zUtilO/WindowsWS.h>
#include <zJson/JsonStream.h>
#include <zAppO/Properties/ApplicationProperties.h>
#include <zDictF/DDChWnd.H>
#include <zDictF/Dddoc.h>
#include <zDictF/DictTreeNode.h>
#include <zEdit2O/UWM.h>
#include <zformf/FrmChWnd.h>
#include <zformf/FormDoc.h>
#include <zformf/FormID.h>
#include <zformf/FormView.h>
#include <zformf/UWM.h>
#include <zOrderF/OrdChWnd.H>
#include <zOrderF/OrdDoc.H>
#include <zOrderF/OSView.H>
#include <zOrderF/UWM.h>
#include <zTableF/resource_shared.h>
#include <zTableF/TabChWnd.h>
#include <zTableF/TabDoc.h>
#include <zTableF/TabView.h>
#include <zTableF/UWM.h>
#include <zCapiO/CapiQuestionManager.h>
#include <Zsrcmgro/Compiler.h>
#include <Zsrcmgro/SrcCode.h>
#include <zInterfaceF/resource_shared.h>
#include <zDesignerF/OnUpdateHints.h>
#include <zDesignerF/resource_shared.h>
#include <zDesignerF/UWM.h>
#include <CSPro/resource.h>
#include <CSPro/UWM.h>
#include <CSPro/AplDoc.h>
#include <CSPro/AplFileAssociationsDlg.h>
#include <CSPro/AplFileAssociationsGrid.h>
#include <CSPro/ChildFrm.h>
#include <CSPro/CSPro.H>
#include <CSPro/MainFrm.h>
#include <CSPro/MDlgBar.h>
#include <CSPro/MsrDoc.h>
#include <CSPro/MsrView.h>
#include <CSPro/MTabCtl.h>
#include <CSPro/ObjTCtrl.h>
