//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by zDictF.rc
//
#define IDD_BEFORE_AFTER_DLG            6001
#define IDD_CAPI_LANGDLG                6002
#define IDD_DICT_PROP_DLGBAR            6003
#define IDD_DICT_PROP_GRID              6004
#define IDD_DICTIONARY_MACROS           6005
#define IDD_FIND_DLG                    6006
#define IDD_GENERATE_VSET               6007
#define IDD_OCCURRENCE                  6008
#define IDD_PRINT_DLG                   6009
#define IDD_RELATION                    6010
#define IDD_SECURITY_OPTIONS            6011
#define IDD_START_POSITION              6012
#define IDD_VSET_LABEL_RENAMER          6013
#define IDI_ITEM_USED                   6014
#define IDI_SUBITEM_USED                6015
#define IDI_REL                         6016
#define IDB_NOTENO                      6017
#define IDB_NOTENO_GRAYED               6018
#define IDB_NOTEYES                     6019
#define IDB_NOTEYES_GRAYED              6020
#define IDS_NOTE_TITLE                  6021
#define IDS_OPTIONS_ABS_WARN            6022
#define IDS_OPTIONS_REL_WARN            6023
#define IDC_ADD                         6500
#define IDC_ADD_ITEMS                   6501
#define IDC_AFTER                       6502
#define IDC_BEFORE                      6503
#define IDC_CASE_SENSITIVE              6504
#define IDC_CHECK_ALLOW_DATA_VIEWER_MODIFICATIONS 6505
#define IDC_CHECK_ALLOW_EXPORTS         6506
#define IDC_COL                         6507
#define IDC_COLPLUS                     6508
#define IDC_COLSTAR                     6509
#define IDC_COLSTARPLUS                 6510
#define IDC_COMBO_PASSWORD_CACHE_MINUTES 6511
#define IDC_COMPACT_DATA_FILE           6512
#define IDC_COPY_DICTIONARY_NAMES       6513
#define IDC_COPY_VALUE_SETS             6514
#define IDC_CREATE_NOTES_DICT           6515
#define IDC_CREATE_SAMPLE               6516
#define IDC_DELETE                      6517
#define IDC_DELETE_VALUE_SETS           6518
#define IDC_DICT_PROP_PLACE_HOLDER      6519
#define IDC_EDIT_PASSWORD_CACHE_MINUTES 6520
#define IDC_GEN_VSET_FROM               6521
#define IDC_GEN_VSET_LABEL              6522
#define IDC_GEN_VSET_NAME               6523
#define IDC_GEN_VSET_TEMPLATE           6524
#define IDC_GEN_VSET_TO                 6525
#define IDC_GEN_VSET_USE_THOUSANDS_SEPARATOR 6526
#define IDC_GENERATE_DATA_FILE          6527
#define IDC_GET_VSET_INTERVAL           6528
#define IDC_INSERT                      6529
#define IDC_INVALID_PERCENT             6530
#define IDC_ITEM_ALL_LANGUAGES          6531
#define IDC_ITEM_LENGTHS                6532
#define IDC_LANGGRID                    6533
#define IDC_MODIFY                      6534
#define IDC_NEXT                        6535
#define IDC_NODROP                      6536
#define IDC_NOTAPPL_PERCENT             6537
#define IDC_NUM_ITEMS                   6538
#define IDC_NUMBER_CASES                6539
#define IDC_OCCGRID                     6540
#define IDC_PASTE_DICTIONARY_NAMES      6541
#define IDC_PASTE_VALUE_SETS            6542
#define IDC_PERCENT                     6543
#define IDC_PREV                        6544
#define IDC_PRINT_BRIEF                 6545
#define IDC_PRINT_DETAILED              6546
#define IDC_PRINT_FILE                  6547
#define IDC_PRINT_LABEL_FIRST           6548
#define IDC_PRINT_NAME_FIRST            6549
#define IDC_PRINT_PRINTER               6550
#define IDC_RANDOM_FILE                 6551
#define IDC_RECORD_LISTING              6552
#define IDC_RELGRID                     6553
#define IDC_REQUIRE_RECORDS_NO          6554
#define IDC_REQUIRE_RECORDS_YES         6555
#define IDC_ROW                         6556
#define IDC_ROWPLUS                     6557
#define IDC_ROWSTAR                     6558
#define IDC_ROWSTARPLUS                 6559
#define IDC_SEARCH_TEXT                 6560
#define IDC_SEQUENTIAL_FILE             6561
#define IDC_SORT_DATA_FILE              6562
#define IDC_START_POS                   6563
#define IDC_START_POSITION              6564
#define IDC_VS_ALL_LANGUAGES            6565
#define IDC_VS_IMAGES                   6566
#define IDC_VSET_LABEL_TEMPLATE         6567
#define ID_COPY_DICT_NAME               43001
#define ID_DICT_ANALYSIS_ITEMS_NO_VALUE_SETS 43002
#define ID_DICT_ANALYSIS_NUMERIC_ITEMS_MISMATCHED_ZF_DC 43003
#define ID_DICT_ANALYSIS_NUMERIC_ITEMS_NO_VALUE_SETS 43004
#define ID_DICT_ANALYSIS_NUMERIC_ITEMS_OVERLAPPING_VALUE_SETS 43005
#define ID_DICTIONARY_MACROS            43006
#define ID_EDIT_ADD                     43007
#define ID_EDIT_ADD_NEXT                43008
#define ID_EDIT_DELETE                  43009
#define ID_EDIT_FLATTEN_OCCURRENCES     43010
#define ID_EDIT_GEN_VALUE_SET           43011
#define ID_EDIT_INSERT                  43012
#define ID_EDIT_LANGUAGES               43013
#define ID_EDIT_MAKE_SUBITEMS           43014
#define ID_EDIT_MODIFY                  43015
#define ID_EDIT_NOTES                   43016
#define ID_EDIT_OCCURRENCELABELS        43017
#define ID_EDIT_RELATION                43018
#define ID_EDIT_SECURITY_OPTIONS        43019
#define ID_MERGE_VS_VALUES              43020
#define ID_OPEN_DATA_FILE0              43021
#define ID_OPEN_DATA_FILE1              43022
#define ID_OPEN_DATA_FILE2              43023
#define ID_OPEN_DATA_FILE3              43024
#define ID_OPEN_DATA_FILE4              43025
#define ID_OPEN_DATA_FILE5              43026
#define ID_OPEN_DATA_FILE6              43027
#define ID_OPEN_DATA_FILE7              43028
#define ID_OPEN_DATA_FILE8              43029
#define ID_OPEN_DATA_FILE9              43030
#define ID_OPEN_OUTPUT_DATA_FILE        43031
#define ID_OPEN_WITH_CSDIFF             43032
#define ID_OPEN_WITH_EXCEL2CSPRO        43033
#define ID_OPEN_WITH_CSEXPORT           43034
#define ID_OPEN_WITH_CSFREQ             43035
#define ID_OPEN_WITH_CSINDEX            43036
#define ID_OPEN_WITH_CSSORT             43037
#define ID_OPTIONS_ABS_REL              43038
#define ID_OPTIONS_DECCHAR              43039
#define ID_OPTIONS_ENABLE_BINARY_ITEMS  43040
#define ID_OPTIONS_ZEROFILL             43041
#define ID_PASTE_VS_LINK                43042
#define ID_REMOVE_VS_LINK               43043
#define ID_REMOVE_VS_ALL_LINKS          43044
#define ID_VIEW_ALIASES                 43045
#define ID_VIEW_DICTIONARY              43046
#define ID_VIEW_LAYOUT                  43047
#define ID_VIEW_PROPERTIES              43048
#define ID_VS_CASE_FORMAT               43049
#define ID_VS_CASE_UPPER                43050
#define ID_VS_CASE_LOWER                43051
#define ID_VS_CASE_MIXED_FIRST_WORD     43052
#define ID_VS_CASE_MIXED_ALL_WORDS      43053
#define ID_VS_MAKE_FIRST_VS             43054
#define ID_VS_REPLACE_VALUE_LABELS      43055

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        6024
#define _APS_NEXT_COMMAND_VALUE         43056
#define _APS_NEXT_CONTROL_VALUE         6568
#define _APS_NEXT_SYMED_VALUE           6024
#endif
#endif
