//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CSEntry.rc
//
#define IDR_CASE_MENU                   101
#define IDR_MAINFRAME                   102
#define IDI_PARTIAL_MOD                 103
#define IDI_EMPTY                       104
#define IDI_PARTIAL_ADD                 105
#define IDI_PARTIAL_VER                 106
#define IDI_COMPLETE                    107
#define IDI_NODE                        108
#define IDI_COMPLETE_VER                109
#define IDI_DELETED                     110
#define IDD_DLG_DISCARD                 111
#define IDD_DLG_DISCARD_MOD             112
#define IDD_DLG_GPS                     113
#define IDD_DLG_PARTIAL                 114
#define IDD_DLG_PARTIAL_MOD             115
#define IDD_GOTO                        116
#define IDD_INTEDTDLG                   117
#define IDD_LEFTVIEW                    118
#define IDD_OPID                        119
#define IDD_PROGRESS_DIALOG             120
#define IDD_PROPPAGE1                   121
#define IDD_PROPPAGE2                   122
#define IDD_QSRCHDLG                    123
#define IDD_STATDLG                     124
#define IDS_INVLDFTYPE                  125
#define IDC_ADD                         1000
#define IDC_BOTH                        1001
#define IDC_DICARD                      1002
#define IDC_FINISH                      1003
#define IDC_GPS_DLG_TEXT                1004
#define IDC_KEYEDIT                     1005
#define IDC_MODIFY                      1006
#define IDC_MSGRAD                      1007
#define IDC_NAME                        1008
#define IDC_NUMCASES                    1009
#define IDC_OCC                         1010
#define IDC_OPID                        1011
#define IDC_OUTOFRANGE                  1012
#define IDC_PAUSE                       1013
#define IDC_PROGRESS_BAR                1014
#define IDC_PROGRESS_MESSAGE            1015
#define IDC_SAVEPARTIAL                 1016
#define IDC_STATGRID                    1017
#define IDC_SUSPEND                     1018
#define IDC_VERFIEDCASES                1019
#define IDC_VERIFIED                    1020
#define ID_ADD                          40001
#define ID_ADD_CASE                     40002
#define ID_ADD_NODE                     40003
#define ID_ADDNODE                      40004
#define ID_ADVTOEND                     40005
#define ID_CAPITOGGLE                   40006
#define ID_CAPITOGGLEALLVARS            40007
#define ID_CASE_LISTING_VIEW_QUESTIONNAIRE 40008
#define ID_DEL_CASE                     40009
#define ID_DELETE_GRPOCC                40010
#define ID_DELETE_NODE                  40011
#define ID_DELETECASE                   40012
#define ID_DELETENODE                   40013
#define ID_EDIT_CASE_NOTE               40014
#define ID_EDIT_FIELD_NOTE              40015
#define ID_EDIT_REVIEW_NOTES            40016
#define ID_ENDGRP                       40017
#define ID_FILE_OPEN_DATORAPL           40018
#define ID_FILE_SETTINGS                40019
#define ID_FILE_SYNCHRONIZE             40020
#define ID_FIND_CASE                    40021
#define ID_FINDCASE                     40022
#define ID_FIRST_CASE                   40023
#define ID_FULLSCREEN                   40024
#define ID_GOTO                         40025
#define ID_INDICATOR_FIELD              40026
#define ID_INDICATOR_MODE               40027
#define ID_INDICATOR_OCC                40028
#define ID_INDICATOR_PARTIALS           40029
#define ID_INDICATOR_SHOW               40030
#define ID_INSERT_CASE                  40031
#define ID_INSERT_GROUPOCC              40032
#define ID_INSERT_GRPOCC_AFTER          40033
#define ID_INSERT_NODE                  40034
#define ID_INSERTNODE                   40035
#define ID_INSRT_CASE                   40036
#define ID_INTEDIT                      40037
#define ID_INTEDITOPTIONS               40038
#define ID_LANGUAGE                     40039
#define ID_LAST_CASE                    40040
#define ID_MODIFY                       40041
#define ID_MODIFY_CASE                  40042
#define ID_NEXT_CASE                    40043
#define ID_NEXT_GROUP                   40044
#define ID_NEXT_GROUP_OCC               40045
#define ID_NEXT_LEVEL                   40046
#define ID_NEXT_LEVEL_OCC               40047
#define ID_NEXT_SCREEN                  40048
#define ID_OPENDAT_FILE                 40049
#define ID_PAUSE                        40050
#define ID_PREV_CASE                    40051
#define ID_PREV_SCREEN                  40052
#define ID_PREVIOUS_PERSISTENT          40053
#define ID_SAVE                         40054
#define ID_SHOW_CASE_LABELS             40055
#define ID_SORTGRPOCC                   40056
#define ID_SORTORDER                    40057
#define ID_STATS                        40058
#define ID_STOP                         40059
#define ID_TOGGLE_CASE_TREE             40060
#define ID_TOGGLE_NAMES                 40061
#define ID_VERIFY                       40062
#define ID_VIEW_ALL_CASES               40063
#define ID_VIEW_CHEAT                   40064
#define ID_VIEW_DUPLICATE_CASES_ONLY    40065
#define ID_VIEW_NOT_DELETED_CASES_ONLY  40066
#define ID_VIEW_PARTIAL_CASES_ONLY      40067
#define ID_VIEW_QUESTIONNAIRE           40068
#define ID_VIEW_REFUSALS                40069

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        126
#define _APS_NEXT_COMMAND_VALUE         40070
#define _APS_NEXT_CONTROL_VALUE         1021
#define _APS_NEXT_SYMED_VALUE           126
#endif
#endif
