//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel2CSPro {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Excel2CSPro.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name {0} has already been used in this dictionary..
        /// </summary>
        internal static string AlreadyUsedName {
            get {
                return ResourceManager.GetString("AlreadyUsedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must save a specification in order to run this tool from the command line..
        /// </summary>
        internal static string CommandLineRequiresSpec {
            get {
                return ResourceManager.GetString("CommandLineRequiresSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you would like to cancel the current operation?.
        /// </summary>
        internal static string ConfirmCancelTask {
            get {
                return ResourceManager.GetString("ConfirmCancelTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cases were converted but some portions of cases were not output because the Excel data was not in order. Sort your data and try the conversion again. The cases out of order include:.
        /// </summary>
        internal static string ConversionDuplicateKeys {
            get {
                return ResourceManager.GetString("ConversionDuplicateKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cases were converted..
        /// </summary>
        internal static string ConversionSuccess {
            get {
                return ResourceManager.GetString("ConversionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cases were converted ({1} added, {2} modified, {3} skipped, and {4} deleted).
        /// </summary>
        internal static string ConversionSuccessDetailed {
            get {
                return ResourceManager.GetString("ConversionSuccessDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you now want to convert data with this dictionary?.
        /// </summary>
        internal static string ConvertDataPostDictionaryCreation {
            get {
                return ResourceManager.GetString("ConvertDataPostDictionaryCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSPro DB Files (*.csdb)|*.csdb|Encrypted CSPro DB Files (*.csdbe)|*.csdbe|Text Data Files (*.dat)|*.dat|All Files (*.*)|*.*.
        /// </summary>
        internal static string DataFileFilter {
            get {
                return ResourceManager.GetString("DataFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output data file: {0}.
        /// </summary>
        internal static string DataLabelFilter {
            get {
                return ResourceManager.GetString("DataLabelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save CSPro Data File.
        /// </summary>
        internal static string DataSaveTitle {
            get {
                return ResourceManager.GetString("DataSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error writing the data file..
        /// </summary>
        internal static string DataWriteError {
            get {
                return ResourceManager.GetString("DataWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSPro Dictionary (*.dcf)|*.dcf.
        /// </summary>
        internal static string DictionaryFileFilter {
            get {
                return ResourceManager.GetString("DictionaryFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string DictionaryLabelFilter {
            get {
                return ResourceManager.GetString("DictionaryLabelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CSPro dictionary.
        /// </summary>
        internal static string DictionaryOpenTitle {
            get {
                return ResourceManager.GetString("DictionaryOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error reading the dictionary..
        /// </summary>
        internal static string DictionaryReadError {
            get {
                return ResourceManager.GetString("DictionaryReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save CSPro dictionary.
        /// </summary>
        internal static string DictionarySaveTitle {
            get {
                return ResourceManager.GetString("DictionarySaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool only works with one-level dictionaries..
        /// </summary>
        internal static string DictionaryUnsupportedNumberLevels {
            get {
                return ResourceManager.GetString("DictionaryUnsupportedNumberLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File: {0}.
        /// </summary>
        internal static string ExcelGroupTitle {
            get {
                return ResourceManager.GetString("ExcelGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error interacting with Excel: {0}.
        /// </summary>
        internal static string ExcelIOError {
            get {
                return ResourceManager.GetString("ExcelIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file: {0}.
        /// </summary>
        internal static string ExcelLabelFilter {
            get {
                return ResourceManager.GetString("ExcelLabelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no data in the worksheet..
        /// </summary>
        internal static string ExcelNoData {
            get {
                return ResourceManager.GetString("ExcelNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Worksheets (*.xlsx;*.xlsm;*.xlsb;*.xls)|*.xlsx;*.xlsm;*.xlsb;*.xls.
        /// </summary>
        internal static string ExcelOpenFilter {
            get {
                return ResourceManager.GetString("ExcelOpenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Excel Workbook.
        /// </summary>
        internal static string ExcelOpenTitle {
            get {
                return ResourceManager.GetString("ExcelOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A numeric item with a decimal component cannot be an ID item..
        /// </summary>
        internal static string InvalidIdNumericDecimal {
            get {
                return ResourceManager.GetString("InvalidIdNumericDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidLength {
            get {
                return ResourceManager.GetString("InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An alpha item must have length between 1-{0}..
        /// </summary>
        internal static string InvalidLengthAlpha {
            get {
                return ResourceManager.GetString("InvalidLengthAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A numeric item must have length between 1-{0}..
        /// </summary>
        internal static string InvalidLengthNumeric {
            get {
                return ResourceManager.GetString("InvalidLengthNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A numeric item&apos;s decimal length must be between 1-{0}..
        /// </summary>
        internal static string InvalidLengthNumericDecimal {
            get {
                return ResourceManager.GetString("InvalidLengthNumericDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length cannot be 0..
        /// </summary>
        internal static string InvalidLengthZero {
            get {
                return ResourceManager.GetString("InvalidLengthZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; is invalid. Do you want to use the suggested alternative, &apos;{1}&apos;?.
        /// </summary>
        internal static string InvalidNameSuggestOther {
            get {
                return ResourceManager.GetString("InvalidNameSuggestOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dictionary must have at least one ID item..
        /// </summary>
        internal static string InvalidNumberIds {
            get {
                return ResourceManager.GetString("InvalidNumberIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item {0} cannot be assigned to as it is overlapped by the assigned item {1}..
        /// </summary>
        internal static string MappingItemOverlap {
            get {
                return ResourceManager.GetString("MappingItemOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unassigned&gt;.
        /// </summary>
        internal static string MappingUnassigned {
            get {
                return ResourceManager.GetString("MappingUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The worksheet {0} is already assigned to a record..
        /// </summary>
        internal static string MappingWorksheetAlreadyAssigned {
            get {
                return ResourceManager.GetString("MappingWorksheetAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting row is not valid. It must be a positive integer..
        /// </summary>
        internal static string PrerunCheckInvalidStartingRow {
            get {
                return ResourceManager.GetString("PrerunCheckInvalidStartingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID item {0} must be mapped for every mapped record..
        /// </summary>
        internal static string PrerunCheckMappingIdsMustBeDefinedForEachRecord {
            get {
                return ResourceManager.GetString("PrerunCheckMappingIdsMustBeDefinedForEachRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must map at least one record to a worksheet..
        /// </summary>
        internal static string PrerunCheckMappingMustDefineRecord {
            get {
                return ResourceManager.GetString("PrerunCheckMappingMustDefineRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must map at least one ID item to a column..
        /// </summary>
        internal static string PrerunCheckMappingNoIdsDefined {
            get {
                return ResourceManager.GetString("PrerunCheckMappingNoIdsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a CSPro output data file..
        /// </summary>
        internal static string PrerunCheckNoDataFile {
            get {
                return ResourceManager.GetString("PrerunCheckNoDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a CSPro dictionary..
        /// </summary>
        internal static string PrerunCheckNoDictionary {
            get {
                return ResourceManager.GetString("PrerunCheckNoDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify an Excel workbook..
        /// </summary>
        internal static string PrerunCheckNoExcel {
            get {
                return ResourceManager.GetString("PrerunCheckNoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel to CSPro Specification File (*.xl2cs)|*.xl2cs.
        /// </summary>
        internal static string SpecFileFilter {
            get {
                return ResourceManager.GetString("SpecFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Excel to CSPro specification file.
        /// </summary>
        internal static string SpecFileOpenTitle {
            get {
                return ResourceManager.GetString("SpecFileOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Excel to CSPro specification file.
        /// </summary>
        internal static string SpecFileSaveTitle {
            get {
                return ResourceManager.GetString("SpecFileSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting row is not a valid number..
        /// </summary>
        internal static string StartingRowInvalid {
            get {
                return ResourceManager.GetString("StartingRowInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting row cannot be less than 1 or greater than {0}..
        /// </summary>
        internal static string StartingRowOutOfRange {
            get {
                return ResourceManager.GetString("StartingRowOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting from Excel to CSPro.
        /// </summary>
        internal static string TitleConvertingData {
            get {
                return ResourceManager.GetString("TitleConvertingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading the Worksheet: {0}.
        /// </summary>
        internal static string TitleReadingWorksheet {
            get {
                return ResourceManager.GetString("TitleReadingWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view the source code here: {0}.
        /// </summary>
        internal static string ViewSourceCode {
            get {
                return ResourceManager.GetString("ViewSourceCode", resourceCulture);
            }
        }
    }
}
