#pragma once

#include <zLogicO/zLogicO.h>
#include <zLogicO/FunctionTable.h>

namespace GF { struct Function; }


namespace ActionInvoker
{
    // the generated hashes of each action name are given in this enum class;
    // ensure that the hash codes of functions that have already been implemented do not change
    enum class Action : int
    {
        // --- CS_AUTOGENERATED_START -----------------------------------------------

        execute                             = 11276,
        registerAccessToken                 = 13052,
        Application_getFormFile             = 49910,
        Application_getQuestionnaireContent = 50614,
        Application_getQuestionText         = 60242,
        Clipboard_getText                   = 47271,
        Clipboard_putText                   = 33682,
        Data_getCase                        = 36632,
        Dictionary_getDictionary            = 43928,
        File_copy                           = 20829,
        File_readBytes                      = 16986,
        File_readLines                      = 50886,
        File_readText                       = 38897,
        File_writeBytes                     = 33892,
        File_writeLines                     = 22252,
        File_writeText                      = 16500,
        Hash_createHash                     = 30568,
        Hash_createMd5                      =  9799,
        Localhost_mapActionResult           = 47687,
        Localhost_mapFile                   = 22391,
        Localhost_mapSymbol                 = 21848,
        Localhost_mapText                   = 62691,
        Logic_eval                          = 50799,
        Logic_getSymbol                     = 44034,
        Logic_getSymbolMetadata             =  4818,
        Logic_getSymbolValue                = 22923,
        Logic_invoke                        = 41927,
        Logic_updateSymbolValue             = 17970,
        Message_formatText                  = 31960,
        Message_getText                     =   449,
        Path_createDirectory                =  9881,
        Path_getDirectoryListing            = 36724,
        Path_getPathInfo                    = 52302,
        Path_getSpecialPaths                = 41709,
        Path_selectFile                     = 28744,
        Path_showFileDialog                 = 23553,
        Settings_getValue                   = 58779,
        Settings_putValue                   = 28521,
        Sqlite_close                        = 14130,
        Sqlite_exec                         = 63594,
        Sqlite_open                         = 58055,
        Sqlite_rekey                        =  3856,
        System_getSharableUri               = 20827,
        System_selectDocument               = 30644,
        UI_alert                            = 31133,
        UI_closeDialog                      = 60265,
        UI_enumerateWebViews                = 30914,
        UI_getDisplayOptions                = 57563,
        UI_getInputData                     = 57200,
        UI_getMaxDisplayDimensions          = 30339,
        UI_postWebMessage                   = 31457,
        UI_setDisplayOptions                = 62732,
        UI_showDialog                       = 49835,
        UI_view                             = 50017,

        // --- CS_AUTOGENERATED_END -------------------------------------------------
    };


    // gets only functions in the CS namespaces
    ZLOGICO_API const std::vector<const Logic::FunctionDetails*>& GetFunctions();

    // gets the name of each of the CS namespaces
    ZLOGICO_API std::map<Logic::FunctionNamespace, const TCHAR*> GetNamespaceNames();

    // gets the generalized function definition for an action if it exists
    ZLOGICO_API const GF::Function* GetFunctionDefinition(Action action);
}
