/* Scintilla source code edit control */
/** @file SciLexer.h
 ** Interface to the added lexer functions in the SciLexer version of the edit control.
 **/
/* Copyright 1998-2002 by Neil Hodgson <neilh@scintilla.org>
 * The License.txt file describes the conditions under which this software may be distributed. */

/* Most of this file is automatically generated from the Scintilla.iface interface definition
 * file which contains any comments about the definitions. HFacer.py does the generation. */

#ifndef SCILEXER_H
#define SCILEXER_H

/* SciLexer features - not in standard Scintilla */

/* ++Autogenerated -- start of section automatically generated from Scintilla.iface */
#define SCLEX_CONTAINER 0
#define SCLEX_NULL 1
#define SCLEX_CSPRO_LOGIC_V0 2
#define SCLEX_CSPRO_LOGIC_V8_0 3
#define SCLEX_CSPRO_MESSAGE_V0 4
#define SCLEX_CSPRO_MESSAGE_V8_0 5
#define SCLEX_CSPRO_REPORT_V0 6
#define SCLEX_CSPRO_REPORT_V8_0 7
#define SCLEX_CSPRO_REPORT_HTML_V0 8
#define SCLEX_CSPRO_REPORT_HTML_V8_0 9
#define SCLEX_CSPRO_PRE80_SPEC_FILE 10
#define SCLEX_CSPRO_DOCUMENT 11
#define SCLEX_CPP 12
#define SCLEX_HTML 13
#define SCLEX_JAVASCRIPT 14
#define SCLEX_JSON 15
#define SCLEX_PERCENT_ENCODING 16
#define SCLEX_SQL 17
#define SCLEX_YAML 18
#define SCLEX_AUTOMATIC 1000

// --------------------------------------------------------------------------
// CSPro
// --------------------------------------------------------------------------
#define SCE_CSPRO_DEFAULT 0
#define SCE_CSPRO_COMMENT 1
#define SCE_CSPRO_COMMENTLINE 2
#define SCE_CSPRO_NUMBER 3
#define SCE_CSPRO_STRING 4
#define SCE_CSPRO_STRING_ESCAPE 5
#define SCE_CSPRO_KEYWORD 6
#define SCE_CSPRO_NUMERROR 7
#define SCE_CSPRO_OPERATOR 8
#define SCE_CSPRO_IDENTIFIER 9
#define SCE_CSPRO_IDENTIFIER_AFTER_DOT 10
#define SCE_CSPRO_DOT_NOTATION_FUNCTION 11
#define SCE_CSPRO_FUNCTION_NAMESPACE_PARENT 12
#define SCE_CSPRO_FUNCTION_NAMESPACE_CHILD 13
#define SCE_CSPRO_IDENTIFIER_AFTER_FUNCTION_NAMESPACE_DOT 14
#define SCE_CSPRO_NAMED_ARGUMENT 15
#define SCE_CSPRO_REPORT_DEFAULT 21
#define SCE_CSPRO_REPORT_MUSTACHE 22
#define SCE_CSPRO_REPORT_TRIP_MUSTACHE 23
#define SCE_CSPRO_REPORT_CSPROLOGIC 24
#define SCE_CSPRO_REPORT_HTML 25
#define SCE_CSPRO_REPORT_HTML_OPTION 26
#define SCE_CSPRO_REPORT_HTML_QUOTE 27
#define SCE_CSPRO_REPORT_HTML_NUM 28
#define SCE_CSPRO_DOCUMENT_TAG 29
#define SCE_CSPRO_DOCUMENT_BOOLEAN_ATTRIBUTE 30
#define SCE_CSPRO_DOCUMENT_ATTRIBUTE 31
#define SCE_CSPRO_DOCUMENT_VALUE 32
#define SCE_CSPRO_PRE80_SPEC_FILE_DEFAULT 0
#define SCE_CSPRO_PRE80_SPEC_FILE_HEADER 1
#define SCE_CSPRO_PRE80_SPEC_FILE_ATTRIBUTE 2

// --------------------------------------------------------------------------
// HTML
// --------------------------------------------------------------------------
#define SCE_H_DEFAULT 0
#define SCE_H_TAG 1
#define SCE_H_TAGUNKNOWN 2
#define SCE_H_ATTRIBUTE 3
#define SCE_H_ATTRIBUTEUNKNOWN 4
#define SCE_H_NUMBER 5
#define SCE_H_DOUBLESTRING 6
#define SCE_H_SINGLESTRING 7
#define SCE_H_OTHER 8
#define SCE_H_COMMENT 9
#define SCE_H_ENTITY 10
#define SCE_H_TAGEND 11
#define SCE_H_XMLSTART 12
#define SCE_H_XMLEND 13
#define SCE_H_SCRIPT 14
#define SCE_H_ASP 15
#define SCE_H_ASPAT 16
#define SCE_H_CDATA 17
#define SCE_H_QUESTION 18
#define SCE_H_VALUE 19
#define SCE_H_XCCOMMENT 20
#define SCE_H_SGML_DEFAULT 21
#define SCE_H_SGML_COMMAND 22
#define SCE_H_SGML_1ST_PARAM 23
#define SCE_H_SGML_DOUBLESTRING 24
#define SCE_H_SGML_SIMPLESTRING 25
#define SCE_H_SGML_ERROR 26
#define SCE_H_SGML_SPECIAL 27
#define SCE_H_SGML_ENTITY 28
#define SCE_H_SGML_COMMENT 29
#define SCE_H_SGML_1ST_PARAM_COMMENT 30
#define SCE_H_SGML_BLOCK_DEFAULT 31
#define SCE_HJ_START 40
#define SCE_HJ_DEFAULT 41
#define SCE_HJ_COMMENT 42
#define SCE_HJ_COMMENTLINE 43
#define SCE_HJ_COMMENTDOC 44
#define SCE_HJ_NUMBER 45
#define SCE_HJ_WORD 46
#define SCE_HJ_KEYWORD 47
#define SCE_HJ_DOUBLESTRING 48
#define SCE_HJ_SINGLESTRING 49
#define SCE_HJ_SYMBOLS 50
#define SCE_HJ_STRINGEOL 51
#define SCE_HJ_REGEX 52
#define SCE_HJA_START 55
#define SCE_HJA_DEFAULT 56
#define SCE_HJA_COMMENT 57
#define SCE_HJA_COMMENTLINE 58
#define SCE_HJA_COMMENTDOC 59
#define SCE_HJA_NUMBER 60
#define SCE_HJA_WORD 61
#define SCE_HJA_KEYWORD 62
#define SCE_HJA_DOUBLESTRING 63
#define SCE_HJA_SINGLESTRING 64
#define SCE_HJA_SYMBOLS 65
#define SCE_HJA_STRINGEOL 66
#define SCE_HJA_REGEX 67
#define SCE_HB_START 70
#define SCE_HB_DEFAULT 71
#define SCE_HB_COMMENTLINE 72
#define SCE_HB_NUMBER 73
#define SCE_HB_WORD 74
#define SCE_HB_STRING 75
#define SCE_HB_IDENTIFIER 76
#define SCE_HB_STRINGEOL 77
#define SCE_HBA_START 80
#define SCE_HBA_DEFAULT 81
#define SCE_HBA_COMMENTLINE 82
#define SCE_HBA_NUMBER 83
#define SCE_HBA_WORD 84
#define SCE_HBA_STRING 85
#define SCE_HBA_IDENTIFIER 86
#define SCE_HBA_STRINGEOL 87
#define SCE_HP_START 90
#define SCE_HP_DEFAULT 91
#define SCE_HP_COMMENTLINE 92
#define SCE_HP_NUMBER 93
#define SCE_HP_STRING 94
#define SCE_HP_CHARACTER 95
#define SCE_HP_WORD 96
#define SCE_HP_TRIPLE 97
#define SCE_HP_TRIPLEDOUBLE 98
#define SCE_HP_CLASSNAME 99
#define SCE_HP_DEFNAME 100
#define SCE_HP_OPERATOR 101
#define SCE_HP_IDENTIFIER 102
#define SCE_HPHP_COMPLEX_VARIABLE 104
#define SCE_HPA_START 105
#define SCE_HPA_DEFAULT 106
#define SCE_HPA_COMMENTLINE 107
#define SCE_HPA_NUMBER 108
#define SCE_HPA_STRING 109
#define SCE_HPA_CHARACTER 110
#define SCE_HPA_WORD 111
#define SCE_HPA_TRIPLE 112
#define SCE_HPA_TRIPLEDOUBLE 113
#define SCE_HPA_CLASSNAME 114
#define SCE_HPA_DEFNAME 115
#define SCE_HPA_OPERATOR 116
#define SCE_HPA_IDENTIFIER 117
#define SCE_HPHP_DEFAULT 118
#define SCE_HPHP_HSTRING 119
#define SCE_HPHP_SIMPLESTRING 120
#define SCE_HPHP_WORD 121
#define SCE_HPHP_NUMBER 122
#define SCE_HPHP_VARIABLE 123
#define SCE_HPHP_COMMENT 124
#define SCE_HPHP_COMMENTLINE 125
#define SCE_HPHP_HSTRING_VARIABLE 126
#define SCE_HPHP_OPERATOR 127

// --------------------------------------------------------------------------
// JavaScript
// --------------------------------------------------------------------------
#define SCE_C_DEFAULT 0
#define SCE_C_COMMENT 1
#define SCE_C_COMMENTLINE 2
#define SCE_C_COMMENTDOC 3
#define SCE_C_NUMBER 4
#define SCE_C_WORD 5
#define SCE_C_STRING 6
#define SCE_C_CHARACTER 7
#define SCE_C_UUID 8
#define SCE_C_PREPROCESSOR 9
#define SCE_C_OPERATOR 10
#define SCE_C_IDENTIFIER 11
#define SCE_C_STRINGEOL 12
#define SCE_C_VERBATIM 13
#define SCE_C_REGEX 14
#define SCE_C_COMMENTLINEDOC 15
#define SCE_C_WORD2 16
#define SCE_C_COMMENTDOCKEYWORD 17
#define SCE_C_COMMENTDOCKEYWORDERROR 18
#define SCE_C_GLOBALCLASS 19
#define SCE_C_STRINGRAW 20
#define SCE_C_TRIPLEVERBATIM 21
#define SCE_C_HASHQUOTEDSTRING 22
#define SCE_C_PREPROCESSORCOMMENT 23
#define SCE_C_PREPROCESSORCOMMENTDOC 24
#define SCE_C_USERLITERAL 25
#define SCE_C_TASKMARKER 26
#define SCE_C_ESCAPESEQUENCE 27

// --------------------------------------------------------------------------
// JSON
// --------------------------------------------------------------------------
#define SCE_JSON_DEFAULT 0
#define SCE_JSON_NUMBER 1
#define SCE_JSON_STRING 2
#define SCE_JSON_STRINGEOL 3
#define SCE_JSON_PROPERTYNAME 4
#define SCE_JSON_ESCAPESEQUENCE 5
#define SCE_JSON_LINECOMMENT 6
#define SCE_JSON_BLOCKCOMMENT 7
#define SCE_JSON_OPERATOR 8
#define SCE_JSON_URI 9
#define SCE_JSON_COMPACTIRI 10
#define SCE_JSON_KEYWORD 11
#define SCE_JSON_LDKEYWORD 12
#define SCE_JSON_ERROR 13

// --------------------------------------------------------------------------
// Percent Encoding
// --------------------------------------------------------------------------
#define SCE_PERCENT_ENCODING_DEFAULT 0
#define SCE_PERCENT_ENCODING_PERCENT 1
#define SCE_PERCENT_ENCODING_HEX 2
#define SCE_PERCENT_ENCODING_BAD_HEX 3
#define SCE_PERCENT_ENCODING_BAD_NOT_UNRESERVED 4

// --------------------------------------------------------------------------
// SQL
// --------------------------------------------------------------------------
#define SCE_SQL_DEFAULT 0
#define SCE_SQL_COMMENT 1
#define SCE_SQL_COMMENTLINE 2
#define SCE_SQL_COMMENTDOC 3
#define SCE_SQL_NUMBER 4
#define SCE_SQL_WORD 5
#define SCE_SQL_STRING 6
#define SCE_SQL_CHARACTER 7
#define SCE_SQL_SQLPLUS 8
#define SCE_SQL_SQLPLUS_PROMPT 9
#define SCE_SQL_OPERATOR 10
#define SCE_SQL_IDENTIFIER 11
#define SCE_SQL_SQLPLUS_COMMENT 13
#define SCE_SQL_COMMENTLINEDOC 15
#define SCE_SQL_WORD2 16
#define SCE_SQL_COMMENTDOCKEYWORD 17
#define SCE_SQL_COMMENTDOCKEYWORDERROR 18
#define SCE_SQL_USER1 19
#define SCE_SQL_USER2 20
#define SCE_SQL_USER3 21
#define SCE_SQL_USER4 22
#define SCE_SQL_QUOTEDIDENTIFIER 23
#define SCE_SQL_QOPERATOR 24

// --------------------------------------------------------------------------
// YAML
// --------------------------------------------------------------------------
#define SCE_YAML_DEFAULT 0
#define SCE_YAML_COMMENT 1
#define SCE_YAML_IDENTIFIER 2
#define SCE_YAML_KEYWORD 3
#define SCE_YAML_NUMBER 4
#define SCE_YAML_REFERENCE 5
#define SCE_YAML_DOCUMENT 6
#define SCE_YAML_TEXT 7
#define SCE_YAML_ERROR 8
#define SCE_YAML_OPERATOR 9

/* --Autogenerated -- end of section automatically generated from Scintilla.iface */

#endif
